function generatorString() {
    return "baseitems.pages.dev " + new Date().toISOString().slice(0, 10);
}

export function generatedByComment() {
    const dashes = "// " + "-".repeat(99);
    return [dashes, "// Generated by " + generatorString(), dashes, ""];
}

export function detailLabel(item) {
    const parts = [];
    if (item.DisplayTabName) parts.push(item.DisplayTabName);
    if (item.DisplayName) parts.push(item.DisplayName);
    return (parts.length > 0 ? parts.join(' > ') + ' ' : '') + `(${item.Name})`;
}

export function detailsToJson(details) {
    return JSON.stringify({ Schema: "BaseItems", Generator: generatorString(), Details: details }, null, 2);
}

export function extractDetails(jsonData) {
    if (jsonData === null || typeof jsonData !== 'object') return null;
    if (jsonData.Schema !== 'BaseItems') return null;

    return Array.isArray(jsonData.Details) ? jsonData.Details : null;
}
