export function generatedByComment() {
    const dashes = "// " + "-".repeat(99);
    return [dashes, "// Generated by baseitems.pages.dev " + new Date().toISOString().slice(0, 10), dashes, ""];
}

export function detailLabel(item) {
    const parts = [];
    if (item.DisplayTabName) parts.push(item.DisplayTabName);
    if (item.DisplayName) parts.push(item.DisplayName);
    return (parts.length > 0 ? parts.join(' > ') + ' ' : '') + `(${item.Name})`;
}
